

import "./globals.css";

import SessionWrap from "./components/SessionWrap";
// import Navbar from "./components/Navbar";
export const metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body >
        <div className="nav">
        {/* <Navbar/> */}
        <SessionWrap>{children}</SessionWrap>
        {/* {children} */}
        
      </div>
      
      </body>
    </html>
  );
} 


